# CI setup to automatically run the jest-test
# after each push on a feature branch / 
# merge on master

# build the project 
# test if needed

# run the tests
unit test:
  stage: test
  script:
    - npm install --progress=false
    - npm run test:all

# deploy (inactive - not needed)